/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package allcoursework;

import java.sql.DriverManager;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author code
 */
public class Dbase extends javax.swing.JFrame {

    /**
     * Creates new form Dbase
     */
    public Dbase(String title) {
        super(title);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        name = new javax.swing.JTextField();
        othername = new javax.swing.JTextField();
        submit = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        stable = new javax.swing.JTable();
        read = new javax.swing.JButton();
        read1 = new javax.swing.JButton();
        read2 = new javax.swing.JButton();
        submit1 = new javax.swing.JButton();
        name1 = new javax.swing.JTextField();
        read3 = new javax.swing.JButton();
        read4 = new javax.swing.JButton();
        read5 = new javax.swing.JButton();
        read6 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                Ajax(evt);
            }
        });

        submit.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        submit.setText("Record");
        submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitActionPerformed(evt);
            }
        });

        stable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Surname"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        stable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                stableMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(stable);
        if (stable.getColumnModel().getColumnCount() > 0) {
            stable.getColumnModel().getColumn(0).setResizable(false);
            stable.getColumnModel().getColumn(0).setPreferredWidth(20);
            stable.getColumnModel().getColumn(1).setResizable(false);
            stable.getColumnModel().getColumn(2).setResizable(false);
        }

        read.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        read.setText("Read");
        read.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                readActionPerformed(evt);
            }
        });

        read1.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        read1.setText("Update");
        read1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                read1ActionPerformed(evt);
            }
        });

        read2.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        read2.setText("Delete");
        read2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                read2ActionPerformed(evt);
            }
        });

        submit1.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        submit1.setText("Exam Question");
        submit1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submit1ActionPerformed(evt);
            }
        });

        read3.setFont(new java.awt.Font("Agency FB", 0, 18)); // NOI18N
        read3.setText("BackUp");
        read3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                read3ActionPerformed(evt);
            }
        });

        read4.setFont(new java.awt.Font("Agency FB", 0, 18)); // NOI18N
        read4.setText("load Backup");
        read4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                read4ActionPerformed(evt);
            }
        });

        read5.setFont(new java.awt.Font("Agency FB", 0, 18)); // NOI18N
        read5.setText("clear Backup");
        read5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                read5ActionPerformed(evt);
            }
        });

        read6.setFont(new java.awt.Font("Agency FB", 0, 18)); // NOI18N
        read6.setText("clear Records");
        read6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                read6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(submit1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(name1, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(othername, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(submit, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(read, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(read1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(read2, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(read3, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(read4, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(read5, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(read6, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(submit1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(othername, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(name1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(submit, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(read, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(read1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(read2, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(read3, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(read4, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(read5, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(read6, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitActionPerformed
       
      String namer = name.getText();
      String namer2 =othername.getText();
      
       if(namer.isEmpty()){
            javax.swing.JOptionPane.showMessageDialog(this, "name is empty");
           // namer.requestFocus();
            return;
       }
       
        if(namer2.isEmpty()){
            javax.swing.JOptionPane.showMessageDialog(this, " Second name is empty");
           // namer.requestFocus();
            return;
       }
       java.sql.Connection con = null;
       String url="jdbc:mysql://localhost/java";
       String user="root";
       String pass="";
       try{
           con=DriverManager.getConnection(url,user,pass);
           
           String query="INSERT INTO students(`surname`,`othername`) VALUES(?,?)";
           
           java.sql.PreparedStatement pst = con.prepareStatement(query);
           
           pst.setString(1, namer);
           pst.setString(2, namer2);
           
           pst.execute();
           
           fetchstudent();
           
           
       }catch(java.sql.SQLException e){
           javax.swing.JOptionPane.showMessageDialog(this, e.getMessage());
       }
    }//GEN-LAST:event_submitActionPerformed

    private void readActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_readActionPerformed
            fetchstudent();
    }//GEN-LAST:event_readActionPerformed

    private void Ajax(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_Ajax
        fetchstudent();
    }//GEN-LAST:event_Ajax

    private void stableMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_stableMousePressed
       try{
           int n=stable.getSelectedRow();
           String strname=stable.getValueAt(n, 1).toString();
           String strothername=stable.getValueAt(n, 2).toString();
           
           name.setText(strname);
           othername.setText(strothername);
           
       }catch(Exception e){
           
       }
    }//GEN-LAST:event_stableMousePressed

    private void read1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_read1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_read1ActionPerformed

    private void read2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_read2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_read2ActionPerformed

    private void submit1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submit1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_submit1ActionPerformed

    private void read3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_read3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_read3ActionPerformed

    private void read4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_read4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_read4ActionPerformed

    private void read5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_read5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_read5ActionPerformed

    private void read6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_read6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_read6ActionPerformed
    // readind data
    public void fetchstudent(){
                       java.sql.Connection con = null;
       String url="jdbc:mysql://localhost/java";
       String user="root";
       String pass="";
       try{
           con=DriverManager.getConnection(url,user,pass);
           
           String query="select * from students";
             java.sql.Statement st = con.createStatement();
             
             java.sql.ResultSet rs = st.executeQuery(query);
             
             // get the table panel 
             DefaultTableModel model = (DefaultTableModel) stable.getModel();
             
             if(rs.isBeforeFirst()){ // count 
               // records found ,so return true 
               
               //do not repeating in table
               int n=model.getRowCount() -1;
               
               for(int i= n ; i>=0 ; i--){
                   model.removeRow(i);
               }
               
               
               while(rs.next()){ // read values line by line
                   
                   //getting value and assing to a new variable
                   int id = rs.getInt("id");
                   String surname =rs.getString("surname");
                   String othername=rs.getString("othername");
                   
                   //store it in a variable
                   Object[] obj = {id,surname,othername};
                   
                   model.addRow(obj);
               }
               
               
                  
             
             }else{ // tale is freee 
                 
                 javax.swing.JOptionPane.showMessageDialog(this , " No records");
             }
          
           
       }catch(java.sql.SQLException e){
           javax.swing.JOptionPane.showMessageDialog(this, e.getMessage());
       }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dbase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dbase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dbase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dbase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dbase("Dbase Tests").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField name;
    private javax.swing.JTextField name1;
    private javax.swing.JTextField othername;
    private javax.swing.JButton read;
    private javax.swing.JButton read1;
    private javax.swing.JButton read2;
    private javax.swing.JButton read3;
    private javax.swing.JButton read4;
    private javax.swing.JButton read5;
    private javax.swing.JButton read6;
    private javax.swing.JTable stable;
    private javax.swing.JButton submit;
    private javax.swing.JButton submit1;
    // End of variables declaration//GEN-END:variables
}
